{% set name = "causalml" %}
{% set version = "0.15.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/causalml-{{ version }}.tar.gz
  sha256: 99f3cf70cdeb19c6a043c24fe555fc8d1e60d8df8f4567ee6aaf56bc85fc2165

build:
  number: 2
  # pytorch doesn't provide a windows build
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cython <=0.29.34  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
  host:
    - pip
    - python
    - cython <=0.29.34
    - setuptools >=41.0.0
    - numpy
    - scikit-learn >=0.22
  run:
    - python
    - setuptools >=41.0.0
    - forestci ==0.6
    - pathos ==0.2.9
    - scipy >=1.4.1
    - matplotlib-base
    - pandas >=0.24.1
    - scikit-learn >=0.22
    - statsmodels >=0.9.0
    - cython <=0.29.34
    - seaborn-base
    - xgboost
    - pydotplus
    - tqdm
    - shap
    - dill
    - lightgbm
    - pygam
    - packaging
    - pytorch
    - pyro-ppl
    - python-graphviz

test:
  imports:
    - causalml
    - causalml.inference.meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://causalml.readthedocs.io/en/latest/?badge=latest
  summary: Causal ML is a Python package that provides a suite of uplift modeling and causal inference methods using machine learning algorithms.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    <a href="https://github.com/uber/causalml">
      <img src="https://raw.githubusercontent.com/uber/causalml/master/docs/_static/img/logo/causalml_logo.png" alt="CausalML banner" />
    </a>

    ``Causal ML`` is a Python package that provides a suite of uplift modeling and causal inference methods using machine learning algorithms based on recent research.
    It provides a standard interface that allows user to estimate the **Conditional Average Treatment Effect** (CATE) or **Individual Treatment Effect** (ITE) from experimental or observational data.
    Essentially, it estimates the causal impact of intervention **T** on outcome **Y** for users with observed features **X**, without strong assumptions on the model form.

    PyPI: [(https://pypi.org/project/causalml/]((https://pypi.org/project/causalml/)
  doc_url: http://causalml.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/uber/causalml

extra:
  recipe-maintainers:
    - jeongyoonlee
    - ppstacy
    - pavelzw
